version: '3'
services:
  database:
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: recipe
      POSTGRES_PASSWORD: recipe
      POSTGRES_DB: recipe_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}