name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test-client:
    name: Build and Test Client
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Dependencies
        working-directory: client/container
        run: npm ci

      - name: Build Container
        working-directory: client/container
        run: npm run build

      - name: Install Dependencies for Form Builder
        working-directory: client/form-builder
        run: npm ci

      - name: Build Form Builder
        working-directory: client/form-builder
        run: npm run build

  build-and-test-server:
    name: Build and Test Server
    runs-on: ubuntu-latest
    
    services:
      database:
        image: postgres:latest
        env:
          POSTGRES_USER: recipe
          POSTGRES_PASSWORD: recipe
          POSTGRES_DB: recipe_db
        ports:
          - 5432:5432

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt
          architecture: x64
      
      - name: Run Docker Compose
        run: docker-compose -f server/demo/docker-compose.yml up -d

      - name: Build and Run Application
        run: |
          cd server/demo
          mvn clean package -DskipTests=true
          
      - name: Wait for Application to Start
        run: |
          echo "Waiting for application to start..."
          sleep 30
      
      - name: Run Application
        run: |
          java -jar server/demo/target/demo-0.0.1-SNAPSHOT.jar

      - name: Stop PostgreSQL Database
        run: |
          cd server/demo
          docker-compose down
